# Generated by Django 5.0.7 on 2024-09-04 17:52

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=300)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_number', models.CharField(max_length=30)),
                ('case_plan', models.TextField(blank=True, null=True)),
                ('Case_loopholes', models.TextField(blank=True, null=True)),
                ('case_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.CharField(blank=True, default=cases.models.Cases.random_number, editable=False, max_length=10, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('adress', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_payment', to='cases.cases')),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_category', to='cases.casescategory'),
        ),
        migrations.CreateModel(
            name='CaseSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_sessions', to='cases.cases')),
            ],
        ),
        migrations.CreateModel(
            name='CasesEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=600)),
                ('task', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_events', to='cases.cases')),
            ],
        ),
        migrations.CreateModel(
            name='CasesFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cases_Files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_files', to='cases.cases')),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to='cases.client'),
        ),
    ]
