# Generated by Django 5.0.7 on 2024-09-09 14:24

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepayment',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_payment', to='cases.cases', verbose_name='Case Payment'),
        ),
        migrations.AlterField(
            model_name='casepayment',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Case_loopholes',
            field=models.TextField(blank=True, null=True, verbose_name='Case loopholes'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_description',
            field=models.TextField(blank=True, null=True, verbose_name='case description'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_id',
            field=models.CharField(blank=True, default=cases.models.Cases.random_number, editable=False, max_length=10, unique=True, verbose_name='case id'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_name',
            field=models.CharField(max_length=300, verbose_name='case name'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=30, verbose_name='case number'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_plan',
            field=models.TextField(blank=True, null=True, verbose_name='case plan'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='case price'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_category', to='cases.casescategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to='cases.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='casescategory',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='casesessions',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='casesessions',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_sessions', to='cases.cases', verbose_name='Case Sessions'),
        ),
        migrations.AlterField(
            model_name='casesessions',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='casesessions',
            name='session_description',
            field=models.TextField(blank=True, null=True, verbose_name='session description'),
        ),
        migrations.AlterField(
            model_name='casesevents',
            name='End_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End_date'),
        ),
        migrations.AlterField(
            model_name='casesevents',
            name='cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_events', to='cases.cases', verbose_name='Case Events'),
        ),
        migrations.AlterField(
            model_name='casesevents',
            name='location',
            field=models.CharField(max_length=600, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='casesevents',
            name='start_date',
            field=models.DateTimeField(verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='casesevents',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='casesfiles',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_files', to='cases.cases', verbose_name='Case Files'),
        ),
        migrations.AlterField(
            model_name='casesfiles',
            name='file',
            field=models.FileField(upload_to='cases_Files', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='whatsapp'),
        ),
    ]
