# Generated by Django 5.0.7 on 2024-09-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_lawyeractive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyeractive',
            options={'permissions': (('Lawyer_Active', 'Lawyer Active'),)},
        ),
    ]
